apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-logging
  namespace: kube-system
  labels:
    component: fluentd-logging
spec:
  template:
    metadata:
      name: fluentd-logging
      namespace: kube-system
      labels:
        component: fluentd-logging
    spec:
      containers:
        - name: fluentd-logging
          image: shrugs/fluentd-logging:latest
          imagePullPolicy: Always
          env:
            - name: FLUENTD_ARGS
              value: -q
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
